openapi: 3.0.0
info:
  title: Audio Transcription API
  description: API for transcribing audio files to text
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /upload-audio:
    post:
      operationId: uploadAudio
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadRequest"
      responses:
        '200':
          description: Successful transcription
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AudioResponse"
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  schemas:
    UploadRequest:
      type: object
      additionalProperties: false
      required:
        - file
      properties:
        file:
          description: >
            The audio file object (not file name) to transcribe, in one of these
            formats: flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, or webm.
          type: string
          format: binary
        model:
          type: string

    AudioResponse:
      type: object
      properties:
        text:
          type: string
          description: The transcribed text
        duration:
          type: number
          description: Duration of the audio in seconds
